// flow-typed signature: ec7c9ae29411debad8c6e8c52f623237
// flow-typed version: <<STUB>>/react-firestore_v^0.8.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-firestore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-firestore" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-firestore/dist/react-firestore.cjs" {
  declare module.exports: any
}

declare module "react-firestore/dist/react-firestore.esm" {
  declare module.exports: any
}

declare module "react-firestore/dist/react-firestore.umd" {
  declare module.exports: any
}

declare module "react-firestore/dist/react-firestore.umd.min" {
  declare module.exports: any
}

declare module "react-firestore/preact/dist/react-firestore.cjs" {
  declare module.exports: any
}

declare module "react-firestore/preact/dist/react-firestore.esm" {
  declare module.exports: any
}

declare module "react-firestore/preact/dist/react-firestore.umd" {
  declare module.exports: any
}

declare module "react-firestore/preact/dist/react-firestore.umd.min" {
  declare module.exports: any
}

// Filename aliases
declare module "react-firestore/dist/react-firestore.cjs.js" {
  declare module.exports: $Exports<"react-firestore/dist/react-firestore.cjs">
}
declare module "react-firestore/dist/react-firestore.esm.js" {
  declare module.exports: $Exports<"react-firestore/dist/react-firestore.esm">
}
declare module "react-firestore/dist/react-firestore.umd.js" {
  declare module.exports: $Exports<"react-firestore/dist/react-firestore.umd">
}
declare module "react-firestore/dist/react-firestore.umd.min.js" {
  declare module.exports: $Exports<
    "react-firestore/dist/react-firestore.umd.min"
  >
}
declare module "react-firestore/preact/dist/react-firestore.cjs.js" {
  declare module.exports: $Exports<
    "react-firestore/preact/dist/react-firestore.cjs"
  >
}
declare module "react-firestore/preact/dist/react-firestore.esm.js" {
  declare module.exports: $Exports<
    "react-firestore/preact/dist/react-firestore.esm"
  >
}
declare module "react-firestore/preact/dist/react-firestore.umd.js" {
  declare module.exports: $Exports<
    "react-firestore/preact/dist/react-firestore.umd"
  >
}
declare module "react-firestore/preact/dist/react-firestore.umd.min.js" {
  declare module.exports: $Exports<
    "react-firestore/preact/dist/react-firestore.umd.min"
  >
}
