// flow-typed signature: 3159277ef69f8e0a711beb29fad72a76
// flow-typed version: <<STUB>>/react-google-button_v^0.5.3/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-google-button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-google-button" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-google-button/dist/react-google-button" {
  declare module.exports: any
}

declare module "react-google-button/dist/react-google-button.min" {
  declare module.exports: any
}

declare module "react-google-button/es/GoogleButton" {
  declare module.exports: any
}

declare module "react-google-button/es/icons" {
  declare module.exports: any
}

declare module "react-google-button/es/index" {
  declare module.exports: any
}

declare module "react-google-button/es/styles" {
  declare module.exports: any
}

declare module "react-google-button/lib/GoogleButton" {
  declare module.exports: any
}

declare module "react-google-button/lib/icons" {
  declare module.exports: any
}

declare module "react-google-button/lib/index" {
  declare module.exports: any
}

declare module "react-google-button/lib/styles" {
  declare module.exports: any
}

declare module "react-google-button/src/GoogleButton" {
  declare module.exports: any
}

declare module "react-google-button/src/icons" {
  declare module.exports: any
}

declare module "react-google-button/src/index" {
  declare module.exports: any
}

declare module "react-google-button/src/styles" {
  declare module.exports: any
}

declare module "react-google-button/test/setup" {
  declare module.exports: any
}

declare module "react-google-button/test/unit/index.spec" {
  declare module.exports: any
}

// Filename aliases
declare module "react-google-button/dist/react-google-button.js" {
  declare module.exports: $Exports<
    "react-google-button/dist/react-google-button"
  >
}
declare module "react-google-button/dist/react-google-button.min.js" {
  declare module.exports: $Exports<
    "react-google-button/dist/react-google-button.min"
  >
}
declare module "react-google-button/es/GoogleButton.js" {
  declare module.exports: $Exports<"react-google-button/es/GoogleButton">
}
declare module "react-google-button/es/icons.js" {
  declare module.exports: $Exports<"react-google-button/es/icons">
}
declare module "react-google-button/es/index.js" {
  declare module.exports: $Exports<"react-google-button/es/index">
}
declare module "react-google-button/es/styles.js" {
  declare module.exports: $Exports<"react-google-button/es/styles">
}
declare module "react-google-button/lib/GoogleButton.js" {
  declare module.exports: $Exports<"react-google-button/lib/GoogleButton">
}
declare module "react-google-button/lib/icons.js" {
  declare module.exports: $Exports<"react-google-button/lib/icons">
}
declare module "react-google-button/lib/index.js" {
  declare module.exports: $Exports<"react-google-button/lib/index">
}
declare module "react-google-button/lib/styles.js" {
  declare module.exports: $Exports<"react-google-button/lib/styles">
}
declare module "react-google-button/src/GoogleButton.js" {
  declare module.exports: $Exports<"react-google-button/src/GoogleButton">
}
declare module "react-google-button/src/icons.js" {
  declare module.exports: $Exports<"react-google-button/src/icons">
}
declare module "react-google-button/src/index.js" {
  declare module.exports: $Exports<"react-google-button/src/index">
}
declare module "react-google-button/src/styles.js" {
  declare module.exports: $Exports<"react-google-button/src/styles">
}
declare module "react-google-button/test/setup.js" {
  declare module.exports: $Exports<"react-google-button/test/setup">
}
declare module "react-google-button/test/unit/index.spec.js" {
  declare module.exports: $Exports<"react-google-button/test/unit/index.spec">
}
