// flow-typed signature: 8e5f3aa9f5f43e2b2b59329cffd892c9
// flow-typed version: <<STUB>>/react-router-scroll-top_v^0.1.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-scroll-top'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-router-scroll-top" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-router-scroll-top/lib/react-router-scroll-top" {
  declare module.exports: any
}

// Filename aliases
declare module "react-router-scroll-top/index" {
  declare module.exports: $Exports<"react-router-scroll-top">
}
declare module "react-router-scroll-top/index.js" {
  declare module.exports: $Exports<"react-router-scroll-top">
}
declare module "react-router-scroll-top/lib/react-router-scroll-top.js" {
  declare module.exports: $Exports<
    "react-router-scroll-top/lib/react-router-scroll-top"
  >
}
