export const SCORE_TEXTS = {
  EASE: [
    "you lazy bastard",
    "your grandma could do it",
    "easy-peasy",
    "piece of cake",
    "it ain't hard",
    "don't sweat too much",
    "it ain't easy",
    "no honey, no money",
    "no pain, no gain",
    "nobel prize level",
    "rocket science, bro",
  ],
  CONFIDENCE: [
    "grow some balls",
    "seriously?",
    "don't quit your job yet",
    "you can do better",
    "we believe in you",
    "it will work (or not)",
    "you got it!",
    "that's a spirit",
    "that's what I'm talking about",
    "like a boss",
    "fuck yeah!",
  ],
  IMPACT: [
    "nobody cares",
    "not really a game-changer",
    "your mom will be proud",
    "useless but cool",
    "almost like this app",
    "so, so",
    "makes life easier",
    "that's an idea",
    "Elon has a competition",
    "Steve would be impressed",
    "once in a lifetime",
  ],
}
